#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def load_config(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def require(config: dict, dotted_key: str):
    value = config
    for part in dotted_key.split("."):
        if not isinstance(value, dict) or part not in value:
            raise SystemExit(f"missing required config value: {dotted_key}")
        value = value[part]
    if value is None or value == "":
        raise SystemExit(f"empty required config value: {dotted_key}")
    return value


def write_json(path: Path, value: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, value: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value, encoding="utf-8")


def render_nats_leaf(config: dict) -> str:
    nats = config["nats"]
    remotes = "\n".join(f'        "{url}"' for url in nats["leaf_remotes"])
    return f"""# Local edge NATS leaf node for Avena RS boxes.
#
# Generated by shared/render-edge-config.py from shared/edge-box.config.json.
# Edit shared/edge-box.config.json, then rerun the renderer.

server_name: "{nats["leaf_server_name"]}"
listen: "{nats["leaf_listen"]}"
http: "{nats["monitor_listen"]}"

jetstream {{
  store_dir: "{nats["jetstream_store_dir"]}"
  domain: "{nats["jetstream_domain"]}"
}}

leafnodes {{
  remotes = [
    {{
      urls: [
{remotes}
      ]
      credentials: "{nats["leaf_credentials_path"]}"
    }}
  ]
}}
"""


def render_alloy_container(config: dict) -> str:
    box_id = config["box_id"]
    return f"""# Grafana Alloy host metrics collector for Avena RS boxes.
#
# Generated by shared/render-edge-config.py from shared/edge-box.config.json.
# Edit shared/edge-box.config.json, then rerun the renderer.

[Unit]
Description=Grafana Alloy host metrics collector
Wants=network-online.target tailscaled.service
After=network-online.target tailscaled.service

[Container]
ContainerName=alloy
Image=docker.io/grafana/alloy:v1.16.2

Network=host
PodmanArgs=--pid=host
SecurityLabelDisable=true
Unmask=ALL

ReadOnly=true
ReadOnlyTmpfs=true

Volume=./config.alloy:/etc/alloy/config.alloy:ro
Volume=alloy.volume:/var/lib/alloy:Z

Volume=/proc:/host/proc:ro
Volume=/sys:/host/sys:ro
Volume=/:/host/root:ro,rslave
Volume=/run/udev/data:/run/udev/data:ro

Environment=NODE_NAME={box_id}

Exec=run --server.http.listen-addr=127.0.0.1:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

[Service]
Restart=always
RestartSec=5s
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
"""


def labjack_kv_config(config: dict) -> dict:
    labjack = config["labjack"]
    nats = config["nats"]
    source = config["source"]
    return {
        "labjack_name": labjack["name"],
        "asset_number": labjack["asset_number"],
        "max_channels": labjack["max_channels"],
        "site_id": config["site_id"],
        "box_id": config["box_id"],
        "source_type": source["type"],
        "source_id": source["id"],
        "nats_subject": nats["root_subject"],
        "nats_stream": nats["stream_name"],
        "rotate_secs": labjack["rotate_secs"],
        "sensor_settings": labjack["sensor_settings"],
    }


def central_client_servers(nats: dict) -> str:
    configured = nats.get("central_servers")
    if isinstance(configured, str) and configured.strip():
        return configured.strip()
    if isinstance(configured, list):
        values = [str(item).strip() for item in configured if str(item).strip()]
        if values:
            return ",".join(values)

    derived = []
    for remote in nats.get("leaf_remotes", []):
        remote = str(remote).strip()
        if not remote:
            continue
        if remote.endswith(":7422"):
            derived.append(f"{remote[:-5]}:4222")
        else:
            derived.append(remote)
    return ",".join(derived)


def streamer_env(config: dict) -> dict:
    nats = config["nats"]
    paths = config["paths"]
    labjack = config["labjack"]
    source = config["source"]
    env = {
        "NATS_SUBJECT": nats["root_subject"],
        "NATS_SERVERS": nats["local_servers"],
        "JS_DOMAIN": nats["jetstream_domain"],
        "ASSET_NUMBER": labjack["asset_number"],
        "SITE_ID": config["site_id"],
        "BOX_ID": config["box_id"],
        "SOURCE_TYPE": source["type"],
        "SOURCE_ID": source["id"],
        "OUTPUT_DIR": paths["output_dir"],
        "NATS_CREDS_FILE": paths["rust_creds_file"],
        "CFG_BUCKET": nats["kv_bucket"],
        "CFG_KEY": nats["kv_key"],
        "CENTRAL_NATS_SERVERS": central_client_servers(nats),
        "CENTRAL_NATS_CREDS_FILE": paths["rust_creds_file"],
        "CENTRAL_CFG_BUCKET": nats["kv_bucket"],
        "CENTRAL_CFG_KEY": nats["kv_key"],
        "LABJACK_IDENTIFIER": labjack.get("identifier", ""),
        "LABJACK_SERIAL": labjack["serial"],
        "LABJACK_NAME": labjack["name"],
        "LABJACK_IP": labjack["ip"],
        "LABJACK_USB_ID": labjack.get("usb_id", "ANY"),
        "LABJACK_OPEN_ORDER": labjack.get("open_order", "ethernet"),
        "EXPORTER_HTTP_URL": paths["exporter_http_url"],
    }

    stream_max_bytes = nats.get("stream_max_bytes")
    if stream_max_bytes is not None:
        env["STREAM_MAX_BYTES"] = stream_max_bytes

    return {"env": env}


def archiver_env(config: dict) -> dict:
    nats = config["nats"]
    paths = config["paths"]
    source = config["source"]
    return {
        "env": {
            "NATS_SUBJECT": nats["root_subject"],
            "NATS_SERVERS": nats["local_servers"],
            "JS_DOMAIN": nats["jetstream_domain"],
            "SITE_ID": config["site_id"],
            "BOX_ID": config["box_id"],
            "SOURCE_TYPE": source["type"],
            "SOURCE_ID": source["id"],
            "NATS_CREDS_FILE": paths["rust_creds_file"],
            "CFG_BUCKET": nats["kv_bucket"],
            "CFG_KEY": nats["kv_key"],
            "PARQUET_DIR": paths["parquet_dir"],
        }
    }


def validate(config: dict):
    required = [
        "site_id",
        "box_id",
        "source.type",
        "source.id",
        "nats.root_subject",
        "nats.local_servers",
        "nats.leaf_server_name",
        "nats.leaf_listen",
        "nats.monitor_listen",
        "nats.jetstream_domain",
        "nats.jetstream_store_dir",
        "nats.leaf_credentials_path",
        "nats.kv_bucket",
        "nats.kv_key",
        "nats.stream_name",
        "paths.rust_creds_file",
        "paths.output_dir",
        "paths.parquet_dir",
        "paths.exporter_http_url",
        "labjack.name",
        "labjack.asset_number",
        "labjack.max_channels",
        "labjack.ip",
        "labjack.serial",
        "labjack.rotate_secs",
        "labjack.sensor_settings.scans_per_read",
        "labjack.sensor_settings.scan_rate_hz",
    ]
    for key in required:
        require(config, key)
    if not config["nats"].get("leaf_remotes"):
        raise SystemExit("nats.leaf_remotes must contain at least one OATS leaf URL")
    stream_max_bytes = config["nats"].get("stream_max_bytes")
    if stream_max_bytes is not None:
        if not isinstance(stream_max_bytes, int) or stream_max_bytes <= 0:
            raise SystemExit("nats.stream_max_bytes must be a positive integer when set")
    channels = config["labjack"]["sensor_settings"].get("channels_enabled", [])
    if not channels:
        raise SystemExit("labjack.sensor_settings.channels_enabled must not be empty")


def main():
    parser = argparse.ArgumentParser(
        description="Render i69 edge box config files from one JSON config."
    )
    parser.add_argument(
        "--config",
        default="shared/edge-box.config.json",
        help="Path to the source config JSON.",
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repository root where generated files should be written.",
    )
    args = parser.parse_args()

    repo = Path(args.repo_root).resolve()
    config_path = (repo / args.config).resolve()
    config = load_config(config_path)
    validate(config)

    write_text(repo / "shared/nats-leaf.conf", render_nats_leaf(config))
    write_text(repo / "shared/alloy.container", render_alloy_container(config))
    write_json(repo / "rust-ljm/streamer.env.json", streamer_env(config))
    write_json(repo / "rust-ljm/archiver.env.json", archiver_env(config))
    write_json(repo / "shared/labjack-kv.generated.json", labjack_kv_config(config))

    print("Rendered edge config files:")
    print("  shared/nats-leaf.conf")
    print("  shared/alloy.container")
    print("  rust-ljm/streamer.env.json")
    print("  rust-ljm/archiver.env.json")
    print("  shared/labjack-kv.generated.json")
    print()
    print(f"Box: {config['box_id']}")
    print(f"Leaf server: {config['nats']['leaf_server_name']}")
    print(f"JetStream domain: {config['nats']['jetstream_domain']}")
    print(f"KV: {config['nats']['kv_bucket']}:{config['nats']['kv_key']}")


if __name__ == "__main__":
    main()
