// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod sampler {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum ScanOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Scan<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Scan<'a> {
  type Inner = Scan<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Scan<'a> {
  pub const VT_FIRST_SAMPLE_UNIX_NS: flatbuffers::VOffsetT = 4;
  pub const VT_SAMPLE_INTERVAL_NS: flatbuffers::VOffsetT = 6;
  pub const VT_ACTUAL_SCAN_RATE_HZ: flatbuffers::VOffsetT = 8;
  pub const VT_SEQUENCE: flatbuffers::VOffsetT = 10;
  pub const VT_VALUES: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Scan { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ScanArgs<'args>
  ) -> flatbuffers::WIPOffset<Scan<'bldr>> {
    let mut builder = ScanBuilder::new(_fbb);
    builder.add_sequence(args.sequence);
    builder.add_actual_scan_rate_hz(args.actual_scan_rate_hz);
    builder.add_sample_interval_ns(args.sample_interval_ns);
    builder.add_first_sample_unix_ns(args.first_sample_unix_ns);
    if let Some(x) = args.values { builder.add_values(x); }
    builder.finish()
  }


  #[inline]
  pub fn first_sample_unix_ns(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Scan::VT_FIRST_SAMPLE_UNIX_NS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn sample_interval_ns(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Scan::VT_SAMPLE_INTERVAL_NS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn actual_scan_rate_hz(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Scan::VT_ACTUAL_SCAN_RATE_HZ, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn sequence(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Scan::VT_SEQUENCE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(Scan::VT_VALUES, None)}
  }
}

impl flatbuffers::Verifiable for Scan<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("first_sample_unix_ns", Self::VT_FIRST_SAMPLE_UNIX_NS, false)?
     .visit_field::<u64>("sample_interval_ns", Self::VT_SAMPLE_INTERVAL_NS, false)?
     .visit_field::<f64>("actual_scan_rate_hz", Self::VT_ACTUAL_SCAN_RATE_HZ, false)?
     .visit_field::<u64>("sequence", Self::VT_SEQUENCE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>("values", Self::VT_VALUES, false)?
     .finish();
    Ok(())
  }
}
pub struct ScanArgs<'a> {
    pub first_sample_unix_ns: u64,
    pub sample_interval_ns: u64,
    pub actual_scan_rate_hz: f64,
    pub sequence: u64,
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
}
impl<'a> Default for ScanArgs<'a> {
  #[inline]
  fn default() -> Self {
    ScanArgs {
      first_sample_unix_ns: 0,
      sample_interval_ns: 0,
      actual_scan_rate_hz: 0.0,
      sequence: 0,
      values: None,
    }
  }
}

pub struct ScanBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ScanBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_first_sample_unix_ns(&mut self, first_sample_unix_ns: u64) {
    self.fbb_.push_slot::<u64>(Scan::VT_FIRST_SAMPLE_UNIX_NS, first_sample_unix_ns, 0);
  }
  #[inline]
  pub fn add_sample_interval_ns(&mut self, sample_interval_ns: u64) {
    self.fbb_.push_slot::<u64>(Scan::VT_SAMPLE_INTERVAL_NS, sample_interval_ns, 0);
  }
  #[inline]
  pub fn add_actual_scan_rate_hz(&mut self, actual_scan_rate_hz: f64) {
    self.fbb_.push_slot::<f64>(Scan::VT_ACTUAL_SCAN_RATE_HZ, actual_scan_rate_hz, 0.0);
  }
  #[inline]
  pub fn add_sequence(&mut self, sequence: u64) {
    self.fbb_.push_slot::<u64>(Scan::VT_SEQUENCE, sequence, 0);
  }
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Scan::VT_VALUES, values);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ScanBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ScanBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Scan<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Scan<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Scan");
      ds.field("first_sample_unix_ns", &self.first_sample_unix_ns());
      ds.field("sample_interval_ns", &self.sample_interval_ns());
      ds.field("actual_scan_rate_hz", &self.actual_scan_rate_hz());
      ds.field("sequence", &self.sequence());
      ds.field("values", &self.values());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Scan`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_scan_unchecked`.
pub fn root_as_scan(buf: &[u8]) -> Result<Scan<'_>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Scan>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Scan` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_scan_unchecked`.
pub fn size_prefixed_root_as_scan(buf: &[u8]) -> Result<Scan<'_>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Scan>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Scan` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_scan_unchecked`.
pub fn root_as_scan_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Scan<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Scan<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Scan` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_scan_unchecked`.
pub fn size_prefixed_root_as_scan_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Scan<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Scan<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Scan and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Scan`.
pub unsafe fn root_as_scan_unchecked(buf: &[u8]) -> Scan<'_> {
  unsafe { flatbuffers::root_unchecked::<Scan>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Scan and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Scan`.
pub unsafe fn size_prefixed_root_as_scan_unchecked(buf: &[u8]) -> Scan<'_> {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Scan>(buf) }
}
#[inline]
pub fn finish_scan_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Scan<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_scan_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Scan<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod sampler
