// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Scan implements flatbuffers.IUnpackableObject<ScanT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Scan {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScan(bb:flatbuffers.ByteBuffer, obj?:Scan):Scan {
  return (obj || new Scan()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScan(bb:flatbuffers.ByteBuffer, obj?:Scan):Scan {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Scan()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

firstSampleUnixNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sampleIntervalNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

actualScanRateHz():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

sequence():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

values(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : 0;
}

valuesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

valuesArray():Float64Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Float64Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startScan(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addFirstSampleUnixNs(builder:flatbuffers.Builder, firstSampleUnixNs:bigint) {
  builder.addFieldInt64(0, firstSampleUnixNs, BigInt('0'));
}

static addSampleIntervalNs(builder:flatbuffers.Builder, sampleIntervalNs:bigint) {
  builder.addFieldInt64(1, sampleIntervalNs, BigInt('0'));
}

static addActualScanRateHz(builder:flatbuffers.Builder, actualScanRateHz:number) {
  builder.addFieldFloat64(2, actualScanRateHz, 0.0);
}

static addSequence(builder:flatbuffers.Builder, sequence:bigint) {
  builder.addFieldInt64(3, sequence, BigInt('0'));
}

static addValues(builder:flatbuffers.Builder, valuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, valuesOffset, 0);
}

static createValuesVector(builder:flatbuffers.Builder, data:number[]|Float64Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createValuesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createValuesVector(builder:flatbuffers.Builder, data:number[]|Float64Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat64(data[i]!);
  }
  return builder.endVector();
}

static startValuesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static endScan(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishScanBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedScanBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createScan(builder:flatbuffers.Builder, firstSampleUnixNs:bigint, sampleIntervalNs:bigint, actualScanRateHz:number, sequence:bigint, valuesOffset:flatbuffers.Offset):flatbuffers.Offset {
  Scan.startScan(builder);
  Scan.addFirstSampleUnixNs(builder, firstSampleUnixNs);
  Scan.addSampleIntervalNs(builder, sampleIntervalNs);
  Scan.addActualScanRateHz(builder, actualScanRateHz);
  Scan.addSequence(builder, sequence);
  Scan.addValues(builder, valuesOffset);
  return Scan.endScan(builder);
}

unpack(): ScanT {
  return new ScanT(
    this.firstSampleUnixNs(),
    this.sampleIntervalNs(),
    this.actualScanRateHz(),
    this.sequence(),
    this.bb!.createScalarList<number>(this.values.bind(this), this.valuesLength())
  );
}


unpackTo(_o: ScanT): void {
  _o.firstSampleUnixNs = this.firstSampleUnixNs();
  _o.sampleIntervalNs = this.sampleIntervalNs();
  _o.actualScanRateHz = this.actualScanRateHz();
  _o.sequence = this.sequence();
  _o.values = this.bb!.createScalarList<number>(this.values.bind(this), this.valuesLength());
}
}

export class ScanT implements flatbuffers.IGeneratedObject {
constructor(
  public firstSampleUnixNs: bigint = BigInt('0'),
  public sampleIntervalNs: bigint = BigInt('0'),
  public actualScanRateHz: number = 0.0,
  public sequence: bigint = BigInt('0'),
  public values: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const values = Scan.createValuesVector(builder, this.values);

  return Scan.createScan(builder,
    this.firstSampleUnixNs,
    this.sampleIntervalNs,
    this.actualScanRateHz,
    this.sequence,
    values
  );
}
}
