#!/usr/bin/env bash

# If sourced, don't leak shell options into the parent shell.
if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
  _RUN_SH_SAVED_OPTS="$(set +o)"
fi

set -eo pipefail

_ENV_SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

: "${NATS_SUBJECT:=avenabox}"
: "${NATS_SERVERS:=nats://nats1.oats:4222,nats://nats2.oats:4222,nats://nats3.oats:4222}"
: "${ASSET_NUMBER:=1001}"
: "${OUTPUT_DIR:=outputs}"
: "${NATS_CREDS_FILE:=${_ENV_SETUP_DIR}/apt.creds}"
: "${CFG_BUCKET:=avenabox}"
: "${CFG_KEY:=labjackd.config.i69-mu1}"
: "${LABJACK_IP:=10.165.77.233}"
: "${LABJACK_USB_ID:=ANY}"
: "${LABJACK_OPEN_ORDER:=ethernet,usb}"
: "${TRIGGER_STREAM:=labjack_triggers}"
: "${VIDEO_BUCKET:=avena_videos}"
: "${VIDEO_TZ:=America/New_York}"
: "${FFMPEG_BIN:=ffmpeg}"
: "${VIDEO_TMP_DIR:=/tmp/avena-video}"
: "${VIDEO_ASSET_NUMBER:=${ASSET_NUMBER}}"
: "${VIDEO_SOURCE_URL:=rtsp://127.0.0.1:8554/avena}"
: "${VIDEO_CAMERA_ID:=default}"
: "${VIDEO_RTSP_TRANSPORT:=tcp}"
: "${VIDEO_SEGMENT_SEC:=5}"
: "${VIDEO_UPLOAD_SETTLE_SEC:=2}"
: "${VIDEO_SCAN_INTERVAL_SEC:=2}"
: "${VIDEO_SPOOL_DIR:=/tmp/avena-video-recorder}"
: "${VIDEO_MULTI_CAMERA_INSTANCES:=cam11,cam10}"
: "${VIDEO_SOURCE_URL_CAM11:=rtsp://admin:1ubuntu9%40@127.0.0.1:8554}"
: "${VIDEO_SOURCE_URL_CAM10:=rtsp://admin:1ubuntu9%40@127.0.0.1:8556}"
: "${VIDEO_ASSET_NUMBER_CAM11:=${ASSET_NUMBER}}"
: "${VIDEO_ASSET_NUMBER_CAM10:=${ASSET_NUMBER}}"
: "${VIDEO_CAMERA_ID_CAM11:=cam11}"
: "${VIDEO_CAMERA_ID_CAM10:=cam10}"
: "${VIDEO_SPOOL_DIR_CAM11:=/tmp/avena-video-recorder-cam11}"
: "${VIDEO_SPOOL_DIR_CAM10:=/tmp/avena-video-recorder-cam10}"
: "${VIDEO_RECORDER_FFMPEG_BIN:=${FFMPEG_BIN}}"
: "${TRIGGER_SUBJECT_FILTER:=${NATS_SUBJECT}.*.trigger.*}"
: "${TRIGGER_CONSUMER_DURABLE:=clip_worker}"
: "${TRIGGER_STATE_BUCKET:=video_trigger_events}"
: "${CLIP_PRE_SEC:=5}"
: "${CLIP_POST_SEC:=5}"
: "${CLIP_PROCESS_LAG_SEC:=15}"
: "${CLIP_COMPACTION_INTERVAL_SEC:=3600}"
: "${CLIP_WORKER_POLL_INTERVAL_SEC:=2}"
: "${CLIP_OUTPUT_PREFIX:=clips}"
: "${CLIP_CAMERA_IDS:=}"
: "${RAW_RETENTION_SEC:=172800}"
: "${EXPORTER_HTTP_URL:=http://127.0.0.1:9001}"
: "${ROLE:=server}"

export NATS_SUBJECT NATS_SERVERS ASSET_NUMBER OUTPUT_DIR NATS_CREDS_FILE CFG_BUCKET CFG_KEY LABJACK_IP LABJACK_USB_ID LABJACK_OPEN_ORDER TRIGGER_STREAM
export VIDEO_BUCKET VIDEO_TZ FFMPEG_BIN VIDEO_TMP_DIR VIDEO_ASSET_NUMBER VIDEO_SOURCE_URL VIDEO_CAMERA_ID VIDEO_RTSP_TRANSPORT VIDEO_SEGMENT_SEC VIDEO_UPLOAD_SETTLE_SEC VIDEO_SCAN_INTERVAL_SEC VIDEO_SPOOL_DIR VIDEO_MULTI_CAMERA_INSTANCES VIDEO_SOURCE_URL_CAM11 VIDEO_SOURCE_URL_CAM10 VIDEO_ASSET_NUMBER_CAM11 VIDEO_ASSET_NUMBER_CAM10 VIDEO_CAMERA_ID_CAM11 VIDEO_CAMERA_ID_CAM10 VIDEO_SPOOL_DIR_CAM11 VIDEO_SPOOL_DIR_CAM10 VIDEO_RECORDER_FFMPEG_BIN
export TRIGGER_SUBJECT_FILTER TRIGGER_CONSUMER_DURABLE TRIGGER_STATE_BUCKET CLIP_PRE_SEC CLIP_POST_SEC CLIP_PROCESS_LAG_SEC CLIP_COMPACTION_INTERVAL_SEC CLIP_WORKER_POLL_INTERVAL_SEC CLIP_OUTPUT_PREFIX CLIP_CAMERA_IDS RAW_RETENTION_SEC
export EXPORTER_HTTP_URL ROLE

if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
  eval "${_RUN_SH_SAVED_OPTS}"
  unset _RUN_SH_SAVED_OPTS
fi

unset _ENV_SETUP_DIR
