// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Entry point generated by `flatc` for `rust-ljm/src/data.fbs`.
 *
 * Re-exports the generated FlatBuffer bindings (the `Scan` table) under the
 * `sampler` namespace. `flatc` overwrites this file when the bindings are
 * regenerated, so edits here are lost. The app imports `Scan` from `./sampler.js`
 * directly (see `flatbuffer-parser.ts`) rather than through this file.
 *
 * @module
 */
export * as sampler from './sampler.js';
